/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../node_modules/mx-components/mx-components.ngfactory';
import * as i3 from 'mx-components';
import * as i4 from '@angular/router';
import * as i5 from '@angular/common';
import * as i6 from '../../../src/app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),2,'app-header',([] as any[]),(null as any),(null as any),(null as any),
      i2.View_ɵa_0,i2.RenderType_ɵa)),i1.ɵdid(114688,(null as any),0,i3.ɵa,([] as any[]),
      (null as any),(null as any)),(_l()(),i1.ɵted(0,[' Teste '])),(_l()(),i1.ɵted((null as any),
      ['\n    \n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['',''])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),15,'nav',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n      '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),5,'a',[['routerLink',
      '/dashboard'],['routerLinkActive','active']],[[1,'target',0],[8,'href',4]],[[(null as any),
      'click']],(_v,en,$event) => {
    var ad:boolean = true;
    if (('click' === en)) {
      const pd_0:any = ((<any>i1.ɵnov(_v,11).onClick($event.button,$event.ctrlKey,
          $event.metaKey,$event.shiftKey)) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),i1.ɵdid(671744,[[2,4]],0,i4.RouterLinkWithHref,[i4.Router,
      i4.ActivatedRoute,i5.LocationStrategy],{routerLink:[0,'routerLink']},(null as any)),
      i1.ɵdid(1720320,(null as any),2,i4.RouterLinkActive,[i4.Router,i1.ElementRef,
          i1.Renderer2,i1.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
          (null as any)),i1.ɵqud(603979776,1,{links:1}),i1.ɵqud(603979776,2,{linksWithHrefs:1}),
      (_l()(),i1.ɵted((null as any),['Dashboard'])),(_l()(),i1.ɵted((null as any),
          ['\n      '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),5,'a',[['routerLink',
          '/heroes'],['routerLinkActive','active']],[[1,'target',0],[8,'href',4]],
          [[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i1.ɵnov(_v,18).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i1.ɵdid(671744,[[4,4]],0,i4.RouterLinkWithHref,
          [i4.Router,i4.ActivatedRoute,i5.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),i1.ɵdid(1720320,(null as any),2,i4.RouterLinkActive,[i4.Router,
          i1.ElementRef,i1.Renderer2,i1.ChangeDetectorRef],{routerLinkActive:[0,'routerLinkActive']},
          (null as any)),i1.ɵqud(603979776,3,{links:1}),i1.ɵqud(603979776,4,{linksWithHrefs:1}),
      (_l()(),i1.ɵted((null as any),['Heroes'])),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(212992,(null as any),
          0,i4.RouterOutlet,[i4.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n  ']))],(_ck,_v) => {
    _ck(_v,2,0);
    const currVal_3:any = '/dashboard';
    _ck(_v,11,0,currVal_3);
    const currVal_4:any = 'active';
    _ck(_v,12,0,currVal_4);
    const currVal_7:any = '/heroes';
    _ck(_v,18,0,currVal_7);
    const currVal_8:any = 'active';
    _ck(_v,19,0,currVal_8);
    _ck(_v,26,0);
  },(_ck,_v) => {
    var _co:i6.AppComponent = _v.component;
    const currVal_0:any = _co.title;
    _ck(_v,6,0,currVal_0);
    const currVal_1:any = i1.ɵnov(_v,11).target;
    const currVal_2:any = i1.ɵnov(_v,11).href;
    _ck(_v,10,0,currVal_1,currVal_2);
    const currVal_5:any = i1.ɵnov(_v,18).target;
    const currVal_6:any = i1.ɵnov(_v,18).href;
    _ck(_v,17,0,currVal_5,currVal_6);
  });
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i6.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i6.AppComponent> = i1.ɵccf('my-app',
    i6.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUFJPSkVUT1MvTk9ERUpTL2V4YW1wbGVzL3RvaC1wdDYvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1BST0pFVE9TL05PREVKUy9leGFtcGxlcy90b2gtcHQ2L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1BST0pFVE9TL05PREVKUy9leGFtcGxlcy90b2gtcHQ2L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1BST0pFVE9TL05PREVKUy9leGFtcGxlcy90b2gtcHQ2L3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8YXBwLWhlYWRlcj4gVGVzdGUgPC9hcHAtaGVhZGVyPlxuICAgIFxuICAgIDxoMT57e3RpdGxlfX08L2gxPlxuICAgIDxuYXY+XG4gICAgICA8YSByb3V0ZXJMaW5rPVwiL2Rhc2hib2FyZFwiIHJvdXRlckxpbmtBY3RpdmU9XCJhY3RpdmVcIj5EYXNoYm9hcmQ8L2E+XG4gICAgICA8YSByb3V0ZXJMaW5rPVwiL2hlcm9lc1wiIHJvdXRlckxpbmtBY3RpdmU9XCJhY3RpdmVcIj5IZXJvZXM8L2E+XG4gICAgPC9uYXY+XG4gICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuICAiLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBQ0k7TUFBQTttQ0FBQSxVQUFBO01BQUEsNkJBQVksZ0NBQW9CO01BQUEsbUJBRWhDO01BQUEsd0VBQUk7YUFBQSx5QkFBYywyQ0FDbEI7YUFBQTtVQUFBLDRDQUFLO01BQUEsZUFDSDtNQUFBO01BQUE7SUFBQTtJQUFBO01BQUE7VUFBQTtNQUFBO0lBQUE7SUFBQTtFQUFBLHVDQUFBOzJDQUFBO2FBQUE7MkNBQUE7VUFBQTtNQUFxRCw4Q0FBYTtVQUFBLGVBQ2xFO1VBQUE7VUFBQTtZQUFBO1lBQUE7Y0FBQTtrQkFBQTtjQUFBO1lBQUE7WUFBQTtVQUFBLHVDQUFBO1VBQUE7VUFBQSxzQkFBQTt5REFBQTtVQUFBO01BQWtELDJDQUFVO01BQ3hELDJDQUNOO1VBQUE7VUFBQSxtREFBQTtVQUFBO2NBQUE7TUFBK0I7SUFQL0I7SUFJSztJQUFILFlBQUcsU0FBSDtJQUEyQjtJQUEzQixZQUEyQixTQUEzQjtJQUNHO0lBQUgsWUFBRyxTQUFIO0lBQXdCO0lBQXhCLFlBQXdCLFNBQXhCO0lBRUY7OztJQUxJO0lBQUE7SUFFRjtJQUFBO0lBQUEsWUFBQSxtQkFBQTtJQUNBO0lBQUE7SUFBQSxZQUFBLG1CQUFBOzs7O29CQ05OO01BQUE7YUFBQTs7OzsifQ==
