/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './dashboard.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from './hero-search.component.ngfactory';
import * as i5 from '../../../src/app/hero-search.service';
import * as i6 from '@angular/http';
import * as i7 from '../../../src/app/hero-search.component';
import * as i8 from '../../../src/app/dashboard.component';
import * as i9 from '../../../src/app/hero.service';
const styles_DashboardComponent:any[] = [i0.styles];
export const RenderType_DashboardComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_DashboardComponent,data:{}});
function View_DashboardComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),9,'a',[['class',
      'col-1-4']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    if (('click' === en)) {
      const pd_0:any = ((<any>i1.ɵnov(_v,1).onClick($event.button,$event.ctrlKey,$event.metaKey,
          $event.shiftKey)) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),i1.ɵpad(2),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','module hero']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n      '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h4',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['',''])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
      i1.ɵted((null as any),['\n  ']))],(_ck,_v) => {
    const currVal_2:any = _ck(_v,2,0,'/detail',_v.context.$implicit.id);
    _ck(_v,1,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,1).target;
    const currVal_1:any = i1.ɵnov(_v,1).href;
    _ck(_v,0,0,currVal_0,currVal_1);
    const currVal_3:any = _v.context.$implicit.name;
    _ck(_v,7,0,currVal_3);
  });
}
export function View_DashboardComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Top Heroes'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','grid grid-pad']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_DashboardComponent_1)),i1.ɵdid(802816,
          (null as any),0,i3.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          2,'hero-search',([] as any[]),(null as any),(null as any),(null as any),
          i4.View_HeroSearchComponent_0,i4.RenderType_HeroSearchComponent)),i1.ɵprd(512,
          (null as any),i5.HeroSearchService,i5.HeroSearchService,[i6.Http]),i1.ɵdid(114688,
          (null as any),0,i7.HeroSearchComponent,[i5.HeroSearchService,i2.Router],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    var _co:i8.DashboardComponent = _v.component;
    const currVal_0:any = _co.heroes;
    _ck(_v,6,0,currVal_0);
    _ck(_v,11,0);
  },(null as any));
}
export function View_DashboardComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'my-dashboard',
      ([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,
      RenderType_DashboardComponent)),i1.ɵdid(114688,(null as any),0,i8.DashboardComponent,
      [i9.HeroService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:i1.ComponentFactory<i8.DashboardComponent> = i1.ɵccf('my-dashboard',
    i8.DashboardComponent,View_DashboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUFJPSkVUT1MvTk9ERUpTL2V4YW1wbGVzL3RvaC1wdDYvc3JjL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1BST0pFVE9TL05PREVKUy9leGFtcGxlcy90b2gtcHQ2L3NyYy9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1BST0pFVE9TL05PREVKUy9leGFtcGxlcy90b2gtcHQ2L3NyYy9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovUFJPSkVUT1MvTk9ERUpTL2V4YW1wbGVzL3RvaC1wdDYvc3JjL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50LnRzLkRhc2hib2FyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMz5Ub3AgSGVyb2VzPC9oMz5cbjxkaXYgY2xhc3M9XCJncmlkIGdyaWQtcGFkXCI+XG4gIDxhICpuZ0Zvcj1cImxldCBoZXJvIG9mIGhlcm9lc1wiICBbcm91dGVyTGlua109XCJbJy9kZXRhaWwnLCBoZXJvLmlkXVwiICBjbGFzcz1cImNvbC0xLTRcIj5cbiAgICA8ZGl2IGNsYXNzPVwibW9kdWxlIGhlcm9cIj5cbiAgICAgIDxoND57e2hlcm8ubmFtZX19PC9oND5cbiAgICA8L2Rpdj5cbiAgPC9hPlxuPC9kaXY+XG48aGVyby1zZWFyY2g+PC9oZXJvLXNlYXJjaD5cbiIsIjxteS1kYXNoYm9hcmQ+PC9teS1kYXNoYm9hcmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNFRTtNQUFBO0lBQUE7SUFBQTtNQUFBO1VBQUE7TUFBQTtJQUFBO0lBQUE7RUFBQSx1Q0FBQTtNQUFBO01BQUEsc0JBQWdDLElBQXFELDJDQUNuRjthQUFBO1VBQUEsMERBQXlCO01BQUEsZUFDdkI7TUFBQSx3RUFBSTthQUFBLHlCQUFrQiwyQ0FDbEI7YUFBQTtJQUh3QjtJQUFoQyxXQUFnQyxTQUFoQzs7SUFBQTtJQUFBO0lBQUEsV0FBQSxtQkFBQTtJQUVRO0lBQUE7Ozs7b0JBSlY7TUFBQSx3RUFBSTthQUFBLGdDQUFlO01BQ25CO1VBQUE7TUFBMkIseUNBQ3pCO1VBQUEsaUVBQUE7VUFBQTtVQUFBLHVDQUlJO01BQ0EsdUNBQ047VUFBQTt5RUFBQTtVQUFBLDBFQUFBO1VBQUE7VUFBQSw2QkFBMkI7OztJQU50QjtJQUFILFdBQUcsU0FBSDtJQU1GOzs7O29CQ1JBO01BQUE7bUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
